In [213]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv("C:/Ruquayya Banu/Data Science/Datasets/adult.csv")
df

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [217]:
col_names = ['age', 'workclass', 'Final_weight', 'education', 'education_num', 'marital_status', 'occupation', 'relationship',
             'race', 'Gender', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income']

In [219]:
df.columns=col_names
df

,age,workclass,Final_weight,education,education_num,marital_status,occupation,relationship,race,Gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [221]:
# summary of the dataset:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32560 non-null  int64
 1   workclass       32560 non-null  object
 2   Final_weight    32560 non-null  int64
 3   education       32560 non-null  object
 4   education_num   32560 non-null  int64
 5   marital_status  32560 non-null  object
 6   occupation      32560 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   Gender          32560 non-null  object
 10  capital_gain    32560 non-null  int64
 11  capital_loss    32560 non-null  int64
 12  hours_per_week  32560 non-null  int64
 13  native_country  32560 non-null  object
 14  income          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

## Categorical features

In [224]:
# finding all the categorical columns
categorical=[var for var in df.columns if df[var].dtype=="O"]

count=len(categorical)
print(f"There are {count} categorical variables")
print("The categorical variables are:\n",categorical)

There are 9 categorical variables
The categorical variables are:
 ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'Gender', 'native_country', 'income']

In [226]:
df[categorical].head()

,workclass,education,marital_status,occupation,relationship,race,Gender,native_country,income
0,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
1,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
2,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
3,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K
4,Private,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,<=50K

In [228]:
# frequency counts of values in categorical features
for var in categorical:
    print(df[var].value_counts())          # "?" ---> what percent of values have this ? in it
                                           # < 50% ---> replace it NAN then fill it with mode
                                           #>50% ---> try to do backward or forward fill or drop it.

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1297
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64
education
HS-grad         10501
Some-college     7291
Bachelors        5354
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64
marital_status
Married-civ-spouse       14976
Never-married            10682
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64
occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3769
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64
relationship
Husband           13193
Not-in-family      8304
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64
race
White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64
Gender
Male      21789
Female    10771
Name: count, dtype: int64
native_country
United-States                 29169
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Laos                             18
Thailand                         18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64
income
<=50K    24719
>50K      7841
Name: count, dtype: int64

In [230]:
# percentage frequency distribution:

for var in categorical:
    print((df[var].value_counts()/len(df))*100)  #native_country,occupation,workclass (contains ?)

workclass
Private             69.705160
Self-emp-not-inc     7.804054
Local-gov            6.428133
?                    5.638821
State-gov            3.983415
Self-emp-inc         3.427518
Federal-gov          2.948403
Without-pay          0.042998
Never-worked         0.021499
Name: count, dtype: float64
education
HS-grad         32.251229
Some-college    22.392506
Bachelors       16.443489
Masters          5.291769
Assoc-voc        4.244472
11th             3.608722
Assoc-acdm       3.277027
10th             2.865479
7th-8th          1.984029
Prof-school      1.769042
9th              1.578624
12th             1.329853
Doctorate        1.268428
5th-6th          1.022727
1st-4th          0.515971
Preschool        0.156634
Name: count, dtype: float64
marital_status
Married-civ-spouse       45.995086
Never-married            32.807125
Divorced                 13.645577
Separated                 3.148034
Widowed                   3.049754
Married-spouse-absent     1.283784
Married-AF-spouse         0.070639
Name: count, dtype: float64
occupation
Prof-specialty       12.714988
Craft-repair         12.589066
Exec-managerial      12.487715
Adm-clerical         11.575553
Sales                11.210074
Other-service        10.119779
Machine-op-inspct     6.148649
?                     5.660319
Transport-moving      4.904791
Handlers-cleaners     4.207617
Farming-fishing       3.052826
Tech-support          2.850123
Protective-serv       1.993243
Priv-house-serv       0.457617
Armed-Forces          0.027641
Name: count, dtype: float64
relationship
Husband           40.519042
Not-in-family     25.503686
Own-child         15.565111
Unmarried         10.583538
Wife               4.815725
Other-relative     3.012899
Name: count, dtype: float64
race
White                 85.426904
Black                  9.594595
Asian-Pac-Islander     3.191032
Amer-Indian-Eskimo     0.955160
Other                  0.832310
Name: count, dtype: float64
Gender
Male      66.919533
Female    33.080467
Name: count, dtype: float64
native_country
United-States                 89.585381
Mexico                         1.974816
?                              1.790541
Philippines                    0.608108
Germany                        0.420762
Canada                         0.371622
Puerto-Rico                    0.350123
El-Salvador                    0.325553
India                          0.307125
Cuba                           0.291769
England                        0.276413
Jamaica                        0.248771
South                          0.245700
China                          0.230344
Italy                          0.224201
Dominican-Republic             0.214988
Vietnam                        0.205774
Guatemala                      0.196560
Japan                          0.190418
Poland                         0.184275
Columbia                       0.181204
Taiwan                         0.156634
Haiti                          0.135135
Iran                           0.132064
Portugal                       0.113636
Nicaragua                      0.104423
Peru                           0.095209
France                         0.089066
Greece                         0.089066
Ecuador                        0.085995
Ireland                        0.073710
Hong                           0.061425
Cambodia                       0.058354
Trinadad&Tobago                0.058354
Laos                           0.055283
Thailand                       0.055283
Yugoslavia                     0.049140
Outlying-US(Guam-USVI-etc)     0.042998
Honduras                       0.039926
Hungary                        0.039926
Scotland                       0.036855
Holand-Netherlands             0.003071
Name: count, dtype: float64
income
<=50K    75.918305
>50K     24.081695
Name: count, dtype: float64

In [232]:
# replacing the ? in the present columns with NAN
#df.replace({"workclass":np.NaN},inplace=True)
df["workclass"] = df["workclass"].str.strip()   # removing white spaces from front and end of the string.
df["workclass"]=df["workclass"].replace("?",np.nan)

In [234]:
df["workclass"].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1297
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [236]:
df["occupation"] = df["occupation"].str.strip()   # removing white spaces from front and end of the string.
df["occupation"]=df["occupation"].replace("?",np.nan)

In [238]:
df["occupation"].value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3769
Sales                3650
Other-service        3295
Machine-op-inspct    2002
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

In [240]:
df["native_country"] = df["native_country"].str.strip()   # removing white spaces from front and end of the string.
df["native_country"]=df["native_country"].replace("?",np.nan)
df["native_country"].value_counts()

native_country
United-States                 29169
Mexico                          643
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Laos                             18
Thailand                         18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [242]:
# imputing the null values into categorical features
df.isnull().sum()

age                  0
workclass         1836
Final_weight         0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
Gender               0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [244]:

df["workclass"].fillna(df["workclass"].mode()[0],inplace=True)

df["occupation"].fillna(df["occupation"].mode()[0],inplace=True)

df.fillna({"native_country":df["native_country"].mode()[0]},inplace=True)  # alternative way

/var/folders/zr/yf7yczb95nv_tkd0pg7hxjww0000gn/T/ipykernel_36766/2835525303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["workclass"].fillna(df["workclass"].mode()[0],inplace=True)
/var/folders/zr/yf7yczb95nv_tkd0pg7hxjww0000gn/T/ipykernel_36766/2835525303.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["occupation"].fillna(df["occupation"].mode()[0],inplace=True)

In [246]:
df.isnull().sum()

age               0
workclass         0
Final_weight      0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
Gender            0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

## Numerical Features:

In [249]:
numerical=[col for col in df.columns if df[col].dtypes != "O"]
numerical

['age',
 'Final_weight',
 'education_num',
 'capital_gain',
 'capital_loss',
 'hours_per_week']

In [251]:
df[numerical].isnull().sum()

age               0
Final_weight      0
education_num     0
capital_gain      0
capital_loss      0
hours_per_week    0
dtype: int64

## Declaring input and target features:

In [254]:
x= df.drop(["income"],axis=1)
y=df["income"]

## Splitting the data into train and test:

In [257]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [259]:
# checking the shape of x_train x_test

x_train.shape

(22792, 14)

In [261]:
x_test.shape

(9768, 14)

In [263]:
x_train

,age,workclass,Final_weight,education,education_num,marital_status,occupation,relationship,race,Gender,capital_gain,capital_loss,hours_per_week,native_country
1935,38,Local-gov,255454,Bachelors,13,Separated,Prof-specialty,Unmarried,Black,Male,0,0,40,United-States
17863,25,Private,374163,12th,8,Married-civ-spouse,Farming-fishing,Husband,Other,Male,0,0,60,Mexico
22456,21,Private,270043,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,16,United-States
8952,41,Private,74775,Bachelors,13,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,0,0,30,Vietnam
28830,49,Private,105614,10th,6,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,50,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28017,30,Private,293936,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,0,0,50,United-States
17728,38,Private,137707,Assoc-voc,11,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,40,United-States
29199,32,Private,159589,HS-grad,9,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,50,United-States
7293,53,Private,141388,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States
17673,36,State-gov,437890,HS-grad,9,Never-married,Exec-managerial,Unmarried,Black,Male,0,0,90,United-States

## Encoding the categorical features:

In [266]:
import category_encoders as ce

In [268]:
import category_encoders as ce
encoders=ce.OneHotEncoder(cols=['workclass', 'education', 'marital_status', 'occupation', 'relationship', 
                                'race', 'Gender', 'native_country'])
x_train_c=encoders.fit_transform(x_train)
x_test_c=encoders.transform(x_test)

In [270]:
x_train_c.head()

,age,workclass_1,workclass_2,workclass_3,workclass_4,workclass_5,workclass_6,workclass_7,workclass_8,Final_weight,...,native_country_31,native_country_32,native_country_33,native_country_34,native_country_35,native_country_36,native_country_37,native_country_38,native_country_39,native_country_40
1935,38,1,0,0,0,0,0,0,0,255454,...,0,0,0,0,0,0,0,0,0,0
17863,25,0,1,0,0,0,0,0,0,374163,...,0,0,0,0,0,0,0,0,0,0
22456,21,0,1,0,0,0,0,0,0,270043,...,0,0,0,0,0,0,0,0,0,0
8952,41,0,1,0,0,0,0,0,0,74775,...,0,0,0,0,0,0,0,0,0,0
28830,49,0,1,0,0,0,0,0,0,105614,...,0,0,0,0,0,0,0,0,0,0

## Feature Scaling:

In [273]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
x_train_n=scaler.fit_transform(x_train[numerical])  
x_train_n# answer will be in the format of array

array([[ 0.05      ,  0.6513325 ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [-0.6       ,  1.65223257, -0.66666667,  0.        ,  0.        ,
         4.        ],
       [-0.8       ,  0.77434028,  0.        ,  0.        ,  0.        ,
        -4.8       ],
       ...,
       [-0.25      , -0.15695739, -0.33333333,  0.        ,  0.        ,
         2.        ],
       [ 0.8       , -0.31041991, -0.33333333,  0.        ,  0.        ,
         0.        ],
       [-0.05      ,  2.18954952, -0.33333333,  0.        ,  0.        ,
        10.        ]])

In [275]:
x_test_n=scaler.transform(x_test[numerical])  # answer will be in form of array

In [277]:
#since x_train_n and x_test_n is in the form of array we cant consider their indexes for the DF conversion so we are taking x_train_c
#and x_test_c indexes reference over here

x_train_n=pd.DataFrame(x_train_n,columns=[numerical],index=x_train.index) 
x_train_n# dataFrame

,age,Final_weight,education_num,capital_gain,capital_loss,hours_per_week
1935,0.05,0.651333,1.000000,0.0,0.0,0.0
17863,-0.60,1.652233,-0.666667,0.0,0.0,4.0
22456,-0.80,0.774340,0.000000,0.0,0.0,-4.8
8952,0.20,-0.872070,1.000000,0.0,0.0,-2.0
28830,0.60,-0.612050,-1.333333,0.0,0.0,2.0
...,...,...,...,...,...,...
28017,-0.35,0.975795,-0.333333,0.0,0.0,2.0
17728,0.05,-0.341456,0.333333,0.0,0.0,0.0
29199,-0.25,-0.156957,-0.333333,0.0,0.0,2.0
7293,0.80,-0.310420,-0.333333,0.0,0.0,0.0
17673,-0.05,2.189550,-0.333333,0.0,0.0,10.0

In [279]:
x_test_n=pd.DataFrame(x_test_n,columns=[numerical],index=x_test.index)

In [281]:
x_train= pd.concat([x_train_c,x_train_n],axis=1)
x_test=pd.concat([x_test_c,x_test_n],axis=1)

In [283]:
x_train

,age,workclass_1,workclass_2,workclass_3,workclass_4,workclass_5,workclass_6,workclass_7,workclass_8,Final_weight,...,native_country_37,native_country_38,native_country_39,native_country_40,"(age,)","(Final_weight,)","(education_num,)","(capital_gain,)","(capital_loss,)","(hours_per_week,)"
1935,38,1,0,0,0,0,0,0,0,255454,...,0,0,0,0,0.05,0.651333,1.000000,0.0,0.0,0.0
17863,25,0,1,0,0,0,0,0,0,374163,...,0,0,0,0,-0.60,1.652233,-0.666667,0.0,0.0,4.0
22456,21,0,1,0,0,0,0,0,0,270043,...,0,0,0,0,-0.80,0.774340,0.000000,0.0,0.0,-4.8
8952,41,0,1,0,0,0,0,0,0,74775,...,0,0,0,0,0.20,-0.872070,1.000000,0.0,0.0,-2.0
28830,49,0,1,0,0,0,0,0,0,105614,...,0,0,0,0,0.60,-0.612050,-1.333333,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28017,30,0,1,0,0,0,0,0,0,293936,...,0,0,0,0,-0.35,0.975795,-0.333333,0.0,0.0,2.0
17728,38,0,1,0,0,0,0,0,0,137707,...,0,0,0,0,0.05,-0.341456,0.333333,0.0,0.0,0.0
29199,32,0,1,0,0,0,0,0,0,159589,...,0,0,0,0,-0.25,-0.156957,-0.333333,0.0,0.0,2.0
7293,53,0,1,0,0,0,0,0,0,141388,...,0,0,0,0,0.80,-0.310420,-0.333333,0.0,0.0,0.0
17673,36,0,0,0,0,1,0,0,0,437890,...,0,0,0,0,-0.05,2.189550,-0.333333,0.0,0.0,10.0

In [285]:
for i in x_train.columns:
    print(i)

age
workclass_1
workclass_2
workclass_3
workclass_4
workclass_5
workclass_6
workclass_7
workclass_8
Final_weight
education_1
education_2
education_3
education_4
education_5
education_6
education_7
education_8
education_9
education_10
education_11
education_12
education_13
education_14
education_15
education_16
education_num
marital_status_1
marital_status_2
marital_status_3
marital_status_4
marital_status_5
marital_status_6
marital_status_7
occupation_1
occupation_2
occupation_3
occupation_4
occupation_5
occupation_6
occupation_7
occupation_8
occupation_9
occupation_10
occupation_11
occupation_12
occupation_13
occupation_14
relationship_1
relationship_2
relationship_3
relationship_4
relationship_5
relationship_6
race_1
race_2
race_3
race_4
race_5
Gender_1
Gender_2
capital_gain
capital_loss
hours_per_week
native_country_1
native_country_2
native_country_3
native_country_4
native_country_5
native_country_6
native_country_7
native_country_8
native_country_9
native_country_10
native_country_11
native_country_12
native_country_13
native_country_14
native_country_15
native_country_16
native_country_17
native_country_18
native_country_19
native_country_20
native_country_21
native_country_22
native_country_23
native_country_24
native_country_25
native_country_26
native_country_27
native_country_28
native_country_29
native_country_30
native_country_31
native_country_32
native_country_33
native_country_34
native_country_35
native_country_36
native_country_37
native_country_38
native_country_39
native_country_40
('age',)
('Final_weight',)
('education_num',)
('capital_gain',)
('capital_loss',)
('hours_per_week',)

In [293]:
# Final_weight is the extra column even after transformation so we are deleting
del x_train["Final_weight"]
del x_test["Final_weight"]
del x_train["age"]

In [295]:
del x_test["age"]

In [297]:
x_train.shape

(22792, 108)

In [299]:
x_test.shape

(9768, 108)

In [301]:
#training the model:
# Gaussian NB
# Multinomail NB
# Bernoulli NB
# some of the column names were in the format of tuple which model doesnot accept it only accept str column name or directly the values.
x_train=x_train.values
x_test=x_test.values

# training a Gaussian NB classifier on the training set

from sklearn.naive_bayes import GaussianNB

# inatantiate the model
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [303]:
# predict the results

y_pred=gnb.predict(x_test)
y_pred

array([' >50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype='<U6')

In [305]:
y_test

11358      >50K
10859      >50K
30948     <=50K
29811     <=50K
18408      >50K
          ...
2253       >50K
29003      >50K
9973      <=50K
2986      <=50K
2366       >50K
Name: income, Length: 9768, dtype: object

In [307]:
# checking the accuracy of the model
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8364045864045864

In [311]:
# creating confusion matrix

from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_pred)

array([[6695,  765],
       [ 833, 1475]])

In [315]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       <=50K       0.89      0.90      0.89      7460
        >50K       0.66      0.64      0.65      2308

    accuracy                           0.84      9768
   macro avg       0.77      0.77      0.77      9768
weighted avg       0.83      0.84      0.84      9768

In [317]:
df["income"].value_counts()  # data is unbalanced

income
<=50K    24719
>50K      7841
Name: count, dtype: int64

In [ ]:
-- precision results minimizing the cause of False positive
-- Recall is important for not missing actual negative values ( minimizing False negative)
-- if a model has very low recall for the minority class the F1 score will be low, accurately reflecting its poor performance for that class.